export const CATEGORY_RELEVANCE_TERMS = {
  people: [
    "person", "people", "man", "woman", "boy", "girl", "family", "friend",
    "baby", "child", "kid", "toddler", "infant", "adult", "teacher",
    "doctor", "mom", "dad", "mother", "father", "parent", "brother",
    "sister", "sibling", "grandma", "grandpa", "grandmother",
    "grandfather", "aunt", "uncle", "cousin", "neighbor", "classmate",
    "coach", "principal", "driver", "farmer", "chef", "baker", "waiter",
    "waitress", "dentist", "vet", "veterinarian", "librarian",
    "babysitter", "nurse", "police", "firefighter", "mail carrier",
    "mailman", "guardian", "caregiver", "therapist", "counselor",
    "student", "senior", "elderly", "king", "queen", "prince",
    "princess", "superhero", "clown", "artist", "musician", "singer",
    "athlete", "worker", "employee", "boss", "customer", "patient",
    "visitor", "guest", "host", "lady", "gentleman", "group", "crowd",
    "team", "class", "audience", "twin",
  ],
  places: [
    "place", "home", "school", "park", "store", "shop", "hospital",
    "restaurant", "playground", "beach", "farm", "city", "house",
    "room", "kitchen", "bathroom", "bedroom", "outside", "inside",
    "town", "zoo", "library", "church", "office", "garden", "yard",
    "pool", "mall", "supermarket", "grocery", "market", "gym",
    "museum", "theater", "cinema", "airport", "station", "bus stop",
    "gas station", "hotel", "bank", "post office", "pharmacy", "salon",
    "barber", "garage", "basement", "attic", "hallway", "living room",
    "dining room", "closet", "porch", "balcony", "driveway",
    "sidewalk", "street", "road", "bridge", "forest", "mountain",
    "lake", "river", "ocean", "sea", "island", "desert", "cave",
    "barn", "stable", "campground", "cabin", "cottage", "apartment",
    "building", "neighborhood", "community", "village", "countryside",
    "field", "meadow", "stadium", "arena", "amusement park",
    "aquarium", "university", "college", "daycare", "nursery",
    "cafeteria", "classroom", "auditorium", "gymnasium",
  ],
  things: [
    "object", "thing", "toy", "book", "ball", "chair", "table", "cup",
    "plate", "phone", "computer", "car", "bike", "box", "bag", "key",
    "door", "window", "pencil", "paper", "shoe", "hat", "bed", "clock",
    "bottle", "spoon", "fork", "bowl", "glass", "pillow", "blanket",
    "towel", "soap", "toothbrush", "toothpaste", "comb", "brush",
    "mirror", "lamp", "light", "television", " tv", "radio", "tablet",
    "laptop", "keyboard", "mouse", "remote", "camera", "watch",
    "wallet", "purse", "backpack", "umbrella", "glasses", "sunglasses",
    "ring", "necklace", "bracelet", "belt", "scissors", "tape", "glue",
    "crayon", "marker", "pen", "notebook", "folder", "envelope",
    "stamp", "letter", "package", "gift", "present", "balloon", "kite",
    "puzzle", "block", "doll", "robot", "game", "drum", "guitar",
    "piano", "instrument", "basket", "bucket", "broom", "mop",
    "vacuum", "washing machine", "dryer", "refrigerator", "fridge",
    "stove", "oven", "microwave", "sink", "toilet", "bathtub",
    "shower", "couch", "sofa", "desk", "shelf", "bookshelf", "drawer",
    "cabinet", "curtain", "rug", "carpet", "wheel", "battery",
    "charger", "cable", "hammer", "tool", "ladder", "map", "calendar",
    "magazine", "newspaper",
  ],
  actions: [
    "action", "verb", "run", "walk", "jump", "eat", "drink", "sleep",
    "play", "read", "write", "sit", "stand", "go", "come", "give",
    "take", "look", "listen", "talk", "help", "wash", "brush", "open",
    "close", "push", "pull", "throw", "catch", "climb", "swim",
    "dance", "sing", "clean", "cook", "draw", "paint", "build", "cry",
    "laugh", "smile", "hug", "kiss", "wave", "point", "clap", "hop",
    "skip", "crawl", "roll", "spin", "turn", "stop", "wait", "watch",
    "wake up", "get up", "sit down", "lie down", "rest", "nap",
    "get dressed", "dress", "tie", "zip", "button", "bathe", "cut",
    "tear", "fold", "wrap", "carry", "hold", "drop", "pick up", "put",
    "put away", "tidy", "sweep", "dust", "water", "plant", "grow",
    "pour", "mix", "stir", "bake", "fry", "boil", "chop", "peel",
    "spread", "share", "trade", "buy", "sell", "pay", "count",
    "measure", "weigh", "compare", "choose", "decide", "ask",
    "answer", "explain", "teach", "learn", "study", "practice",
    "remember", "forget", "think", "know", "understand", "imagine",
    "dream", "wish", "hope", "hurry", "drive", "ride", "fly", "sail",
    "march", "exercise", "stretch", "kick", "bounce", "float", "sink",
    "dive", "splash",
  ],
  feelings: [
    "feeling", "emotion", "happy", "sad", "angry", "anger", "scared",
    "afraid", "tired", "excited", "surprised", "worried", "calm",
    "proud", "shy", "confused", "bored", "sick", "love", "nervous",
    "frustrated", "silly", "lonely", "jealous", "embarrassed",
    "disappointed", "hopeful", "grateful", "thankful", "relieved",
    "curious", "interested", "uncomfortable", "comfortable", "feeling safe",
    "upset", "annoyed", "irritated", "cranky", "grumpy", "cheerful",
    "joyful", "content", "satisfied", "disgusted", "uncertain",
    "unsure", "confident", "brave", "weak", "strong", "hurt",
    "overwhelmed", "stressed", "anxious", "delighted", "amused",
    "playful", "guilty", "ashamed", "regretful", "sorry", "peaceful",
    "relaxed", "energetic", "exhausted", "sleepy", "hungry",
    "thirsty", "full",
  ],
  food: [
    "food", "drink", "eat", "fruit", "vegetable", "apple", "banana",
    "bread", "milk", "water", "juice", "snack", "breakfast", "lunch",
    "dinner", "pizza", "sandwich", "cookie", "cake", "cereal",
    "cheese", "egg", "chicken", "rice", "pasta", "orange", "grape",
    "strawberry", "watermelon", "pear", "peach", "pineapple", "mango",
    "berry", "carrot", "potato", "tomato", "corn", "broccoli",
    "lettuce", "salad", "soup", "meat", "beef", "pork", "fish",
    "shrimp", "bacon", "sausage", "hot dog", "hamburger", "burger",
    "fries", "chips", "popcorn", "pretzel", "cracker", "muffin",
    "donut", "pie", "ice cream", "candy", "chocolate", "yogurt",
    "butter", "jam", "jelly", "peanut butter", "honey", "syrup",
    "sugar", "salt", "pepper", "sauce", "ketchup", "mustard",
    "mayo", "soda", "coffee", "tea", "lemonade", "smoothie",
    "milkshake", "oatmeal", "pancake", "waffle", "toast", "bagel",
    "bun", "roll", "noodle", "taco", "burrito", "sushi", "dumpling",
    "spaghetti", "macaroni", "treat", "meal", "picnic", "barbecue",
  ],
  animals: [
    "animal", "dog", "cat", "bird", "fish", "horse", "cow", "pig",
    "sheep", "chicken", "duck", "rabbit", "lion", "tiger", "bear",
    "elephant", "monkey", "giraffe", "zebra", "snake", "frog",
    "turtle", "farm", "pet", "vulture", "eagle", "owl", "deer", "fox",
    "wolf", "goat", "donkey", "mouse", "rat", "hamster", "guinea pig",
    "squirrel", "chipmunk", "raccoon", "skunk", "beaver", "otter",
    "dolphin", "whale", "shark", "seal", "penguin", "crab", "lobster",
    "octopus", "jellyfish", "starfish", "seahorse", "butterfly",
    "bee", "ant", "spider", "ladybug", "worm", "caterpillar",
    "dragonfly", "grasshopper", "cricket", "beetle", "moth", "fly",
    "mosquito", "kangaroo", "koala", "panda", "hippo", "rhino",
    "crocodile", "alligator", "lizard", "gecko", "chameleon",
    "tortoise", "camel", "llama", "alpaca", "buffalo", "bison",
    "moose", "elk", "hedgehog", "bat", "parrot", "peacock",
    "flamingo", "swan", "goose", "turkey", "rooster", "hen", "chick",
    "kitten", "puppy", "cub", "calf", "foal", "lamb", "piglet",
    "wildlife", "insect", "bug", "reptile", "mammal",
  ],
  clothing: [
    "clothing", "clothes", "shirt", "pants", "dress", "shoe", "sock",
    "hat", "coat", "jacket", "sweater", "skirt", "shorts", "glove",
    "scarf", "boot", "pajama", "underwear", "t-shirt", "blouse",
    "sweatshirt", "hoodie", "vest", "tie", "suit", "uniform",
    "swimsuit", "bathing suit", "raincoat", "snowsuit", "mittens",
    "sandals", "sneakers", "slippers", "flip flops", "cap", "beanie",
    "helmet", "buckle", "zipper", "button", "pocket", "sleeve",
    "collar", "apron", "robe", "nightgown", "onesie", "bib", "diaper",
    "tights", "leggings", "jeans", "overalls", "romper", "jumpsuit",
    "costume", "cape", "goggles", "earmuffs",
  ],
};

export const CATEGORY_EXCLUDE_TERMS = {
  places: [
    "medal", "place setting", "1st place", "2nd place", "3rd place",
    "first place", "second place", "third place", "placeholder",
  ],
  people: ["flag"],
};
